package com.ad364.bc_tables;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TravelProfile implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean isTravel;
	private java.lang.Integer travelPercentage;

	public TravelProfile() {
	}

	public java.lang.Boolean getIsTravel() {
		return this.isTravel;
	}

	public void setIsTravel(java.lang.Boolean isTravel) {
		this.isTravel = isTravel;
	}

	public java.lang.Integer getTravelPercentage() {
		return this.travelPercentage;
	}

	public void setTravelPercentage(java.lang.Integer travelPercentage) {
		this.travelPercentage = travelPercentage;
	}

	public TravelProfile(java.lang.Boolean isTravel,
			java.lang.Integer travelPercentage) {
		this.isTravel = isTravel;
		this.travelPercentage = travelPercentage;
	}

}